title: API Evangelist Tools
description: Mapping the technical details of API operations to the human tool.
lang: en

baseurl: ""

# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
permalink: /:categories/:year/:month/:day/:title/

url: "https://contracts.apievangelist.com"

logo: https://kinlane-productions2.s3.amazonaws.com/api-evangelist-logos/api-evangelist-logo-butterfly.png

navbar:
    sticky:         true
    search:         true
  
author:
    name:           Kin Lane
    title:          API Evangelist
    avatar:         https://kinlane-productions2.s3.amazonaws.com/kin-lane/kin-lane-cartoon-questioning.png

authors:
    kin:
      name:         Kin Lane
      title:        API Evangelist
      avatar:       https://kinlane-productions2.s3.amazonaws.com/kin-lane/kin-lane-cartoon-questioning.png
      email:       'kinlane@postman.com'
      affiliation: 'API Evangelist'
      github:      'kinlane'
      linkedin:    'in/kinlane'       

social:
    email:
    website:
    facebook:       
    flickr:
    dribbble:
    github:         https://github.com/api-evangelist
    googleplus:
    instagram:     
    linkedin:       https://www.linkedin.com/in/kinlane/
    pinterest:
    twitter:        
    vimeo:          
    youtube:        https://www.youtube.com/c/KinLane
    mastodon:       

# Share button
share:
    post:           true # Display share buttons on a post page
    doc:            true # Display share buttons on a doc page
    twitter:        username # Enable by adding Twitter handle 
    facebook:       true # Enable by setting true (Facebook handle not required)

# Default footer image settings
footer:
    copyright:      API Evangelist

# Path to post content assets directory i.e post images, pdfs etc
uploads:            /uploads/

# Build settings
markdown:           kramdown
highlighter:        rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-avatar
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  
sass:
  style: compressed

apisApiBaseUrl: 'https://apis-api.apievangelist.com'
basesApiBaseUrl: 'https://bases-api.apievangelist.com'
blueprintsApiBaseUrl: 'https://blueprints-api.apievangelist.com'
contractsApiBaseUrl: 'https://contracts-api.apievangelist.com'
conversationsApiBaseUrl: 'https://conversations-api.apievangelist.com'
customersApiBaseUrl: 'https://customers-api.apievangelist.com'
discoveryApiBaseUrl: 'https://discovery-api.apievangelist.com'
evidenceApiBaseUrl: 'https://evidence-api.apievangelist.com'
extensionsApiBaseUrl: 'https://extensions-api.apievangelist.com'
guidancesApiBaseUrl: 'https://guidance-api.apievangelist.com'
headersApiBaseUrl: 'https://headers-api.apievangelist.com'
organizationsApiBaseUrl: 'https://organizations-api.apievangelist.com'
overlaysApiBaseUrl: 'https://overlays-api.apievangelist.com'
parametersApiBaseUrl: 'https://parameters-api.apievangelist.com'
partnersApiBaseUrl: 'https://partners-api.apievangelist.com'
policiesApiBaseUrl: 'https://policies-api.apievangelist.com'
postsApiBaseUrl: 'https://posts-api.apievangelist.com'
propertiesApiBaseUrl: 'https://properties-api.apievangelist.com'
responsesApiBaseUrl: 'https://responses-api.apievangelist.com'
rulesApiBaseUrl: 'https://rules-api.apievangelist.com'
schemaApiBaseUrl: 'https://schema-api.apievangelist.com'
servicesApiBaseUrl: 'https://services-api.apievangelist.com'
standardsApiBaseUrl: 'https://standards-api.apievangelist.com'
storiesApiBaseUrl: 'https://stories-api.apievangelist.com'
strategiesApiBaseUrl: 'https://strategies-api.apievangelist.com'
utilitiesApiBaseUrl: 'https://utilitiesapi.apievangelist.com'
vocabulariesApiBaseUrl: 'https://vocabularies-api.apievangelist.com'

collections:
  store:
    output:         true

defaults:
  - scope:
      path:         ""
      type:         store
    values:
      layout:       store