#!/usr/bin/env python3
"""Write the tools-per-standard index the standards site renders.

The link between a standard and its tooling has to be two-way or it is not navigable. A tool page
already names the standards it implements. This writes the other direction — a data file the
standards repo reads to show, on each standard's page, the open source tools that implement it and
what each one does to it.

Generated, never hand-edited: the source of truth is tools/scripts/spec-tools.yml plus whatever
the tools store actually publishes. A standard with no tooling gets no entry, and its page shows
nothing rather than an empty section.

    link_standards.py --dry
    link_standards.py
"""
import json
import os
import re
import sys
from datetime import date

import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
TOOLS_REPO = os.path.dirname(HERE)
STORE = os.path.join(TOOLS_REPO, "_store")
STANDARDS = os.path.abspath(os.path.join(TOOLS_REPO, "..", "standards"))
OUT = os.path.join(STANDARDS, "_data", "spec_tools.yml")


def front_matter(path):
    t = open(path).read()
    m = re.match(r"^---\n(.*?)\n---", t, re.S)
    return yaml.safe_load(m.group(1)) if m else {}


def main():
    dry = "--dry" in sys.argv
    if not os.path.isdir(STANDARDS):
        print(f"standards repo not found at {STANDARDS}")
        return 1

    by_standard = {}
    for f in sorted(os.listdir(STORE)):
        if not f.endswith(".md"):
            continue
        fm = front_matter(os.path.join(STORE, f))
        for s in fm.get("specifications") or []:
            rec = {
                "slug": fm.get("slug") or f[:-3],
                "title": fm.get("title"),
                "url": f"https://tools.apievangelist.com/store/{fm.get('slug') or f[:-3]}/",
                "description": (fm.get("description") or "").strip(),
                "role": s.get("role"),
                "license": fm.get("license"),
                "openSource": fm.get("openSource", False),
                "repository": fm.get("repository"),
                "stars": fm.get("stars") or 0,
            }
            if s.get("also"):
                rec["also"] = s["also"]
            if fm.get("companyCount"):
                rec["companyCount"] = fm["companyCount"]
            by_standard.setdefault(s["slug"], []).append(rec)

    for slug in by_standard:
        by_standard[slug].sort(key=lambda r: -(r.get("stars") or 0))

    doc = {
        "note": ("Open source tools implementing each standard, generated from "
                 "tools.apievangelist.com. `role` is the controlled vocabulary at "
                 "https://tools.apievangelist.com/roles.json — what the tool does TO the "
                 "specification. Do not hand-edit: regenerate with "
                 "tools/scripts/link_standards.py."),
        "generated": date.today().isoformat(),
        "source": "https://tools.apievangelist.com/tools.json",
        "standards": by_standard,
    }

    total = sum(len(v) for v in by_standard.values())
    print(f"{'DRY RUN — ' if dry else ''}{len(by_standard)} standards, {total} tool links")
    for slug, tools in sorted(by_standard.items(), key=lambda kv: -len(kv[1])):
        print(f"  {slug:<24} {len(tools):>2} tools  {', '.join(t['title'] for t in tools[:4])}"
              f"{'…' if len(tools) > 4 else ''}")
    # The tools site's own "By specification" index, so the front page can be built from data
    # rather than a hand-maintained list that drifts the moment a tool is added.
    spec_meta = {s["spec"]: s for s in
                 yaml.safe_load(open(os.path.join(HERE, "spec-tools.yml")))["specifications"]}
    index = {
        "note": "Generated by tools/scripts/link_standards.py. Do not hand-edit.",
        "generated": date.today().isoformat(),
        "specifications": [
            {
                "slug": slug,
                "name": (spec_meta.get(slug) or {}).get("name", slug),
                "count": len(tools),
                "tools": [t["title"] for t in tools],
            }
            for slug, tools in sorted(by_standard.items(), key=lambda kv: (-len(kv[1]), kv[0]))
        ],
    }
    local_out = os.path.join(TOOLS_REPO, "_data", "spec_index.yml")

    if not dry:
        os.makedirs(os.path.dirname(OUT), exist_ok=True)
        with open(OUT, "w") as f:
            yaml.safe_dump(doc, f, sort_keys=False, allow_unicode=True, width=100)
        print(f"\nwrote {os.path.relpath(OUT, os.path.dirname(TOOLS_REPO))}")
        with open(local_out, "w") as f:
            yaml.safe_dump(index, f, sort_keys=False, allow_unicode=True, width=100)
        print(f"wrote {os.path.relpath(local_out, TOOLS_REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
